[package]
name = "sprite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bytes_ext = { workspace = true }
dune = { workspace = true }
framebuffer = { workspace = true }
