[package]
name = "lipsync"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes_ext = { workspace = true }
clap = { workspace = true, features = ["derive"] }
dune = { workspace = true }
framebuffer = { workspace = true }
room_renderer = { workspace = true }
sprite = { workspace = true }
