[package]
name = "savegame"
version = "0.0.0"
edition.workspace = true

[[bin]]
name = "display_savegame"
path = "src/bin/display_savegame.rs"

[dependencies]
bytes_ext = { workspace = true }
dune = { workspace = true }
serde = { workspace = true }
bin_read = { workspace = true }
