[package]
name = "room_renderer"
version = "0.0.0"
edition.workspace = true

[dependencies]
bytes_ext = { workspace = true }
dune = { workspace = true }
serde = { workspace = true, features = ["derive"] }
