[package]
name = "draw_night_attack"
version = "0.1.0"
edition = "2024"

[dependencies]
dune = { workspace = true }
framebuffer = { workspace = true }
num = { workspace = true }
sprite = { workspace = true }
